from __future__ import annotations

import math
import re
from collections import Counter, deque
from itertools import chain
from numbers import Real

from .split import split
from .utils.validator import validate_cs_tag, validate_long_format


def split_deletion(cs_tag: str) -> list[str]:
    match = re.match(r"-(?P<nucleotides>[acgtn]+)$", cs_tag)
    if match:
        nucleotides = match.group("nucleotides")
        return [f"-{n}" for n in nucleotides]
    return [cs_tag]


def expand_deletion_tags(tags_combined: list[str]) -> list[str]:
    cs_tags_expand_deletion: list[str] = []
    for tag in tags_combined:
        cs_tags_expand_deletion.extend(split_deletion(tag))
    return cs_tags_expand_deletion


def split_cs_tags(cs_tags: list[str]) -> list[list[str]]:
    """
    Split and process each cs tag in cs_tags.

    Args:
        cs_tags (list[str]): list of cs tags in the long format.

    Returns:
        list[list[str]]: list of processed cs tags.
    """
    cs_tags_splitted: list[list[str]] = []
    for cs_tag in cs_tags:
        # Remove the prefix "cs:Z:" if present
        cs_tag = cs_tag.replace("cs:Z:", "")

        # Split the cs tag using special symbols (-, *, ~, =)
        # insertion symbol (+) is ignored because it is not observed in reference sequence
        tags_splitted = re.split(r"([-*~=])", cs_tag)[1:]
        # Combine the symbol with the corresponding sequence
        tags_combined = [
            symbol + sequence
            for symbol, sequence in zip(
                tags_splitted[0::2], tags_splitted[1::2], strict=False
            )
        ]
        tags_combined = expand_deletion_tags(tags_combined)

        # Remove the "=" symbols, as they are not needed for further processing
        cleaned_tags = [tag.replace("=", "") for tag in tags_combined]
        # Further split the tags by the base letters (A, C, G, T)
        further_tags_splitted = [re.split(r"(?=[ACGT])", tag) for tag in cleaned_tags]
        # Remove any empty strings generated by the split
        non_empty_tags = [
            [elem for elem in tag if elem] for tag in further_tags_splitted
        ]
        # Flatten the list of lists into a single list
        flat_tags = list(chain.from_iterable(non_empty_tags))
        cs_tags_splitted.append(flat_tags)
    return cs_tags_splitted


def normalize_positions(positions: list[int]) -> list[int]:
    """
    Normalize the positions in the given list by shifting them so that the minimum position becomes zero.
    """
    pos_min = min(positions)
    return [pos - pos_min for pos in positions]


def normalize_read_lengths(
    cs_tags: list[str], positions: list[int]
) -> list[list[str | None]]:
    """
    Normalize the lengths of each read in cs_tags based on their starts positions. If the length is insufficient, fill in with `None`.

    Args:
        cs_tags (list[str]): list of cs tags.
        positions (list[int]): Starting positions of each read.

    Returns:
        list[list[str | None]]: list of lists representing the reads, now normalized
        to the same length.
    """
    cs_tags_split = split_cs_tags(cs_tags)
    cs_tags_deque: list[deque[str | None]] = [deque(cs) for cs in cs_tags_split]
    positions_normalized = normalize_positions(positions)
    cs_maxlen = max(
        len(cs) + pos
        for cs, pos in zip(cs_tags_deque, positions_normalized, strict=False)
    )

    for i, pos in enumerate(positions_normalized):
        if pos > 0:
            cs_tags_deque[i].extendleft([None] * pos)
        if len(cs_tags_deque[i]) < cs_maxlen:
            cs_tags_deque[i].extend([None] * (cs_maxlen - len(cs_tags_deque[i])))
    normalized_tags = [list(cs) for cs in cs_tags_deque]
    return normalized_tags


def condense_deletions(s: str) -> str:
    # Pattern for detecting continuous nucleotide deletions
    pattern = r"(-[acgtn])+"

    # Function to replace the matched pattern
    def replacement(match: re.Match[str]) -> str:
        # Remove hyphens and concatenate the nucleotides
        condensed_nucleotides = match.group(0).replace("-", "")
        return f"-{condensed_nucleotides}"

    # Use the regular expression to substitute the pattern with its condensed form
    return re.sub(pattern, replacement, s)


def _is_mutation_tag(tag: str) -> bool:
    """Return whether a normalized per-position tag represents a mutation."""
    return re.fullmatch(r"[ACGTN]", tag) is None


def _format_consensus(cs_consensus: list[str]) -> str:
    consensus_string = condense_deletions("".join(cs_consensus))
    # Append "=" to runs of reference bases.
    return re.sub(r"([ACGTN]+)", r"=\1", consensus_string)


def _get_consensus_and_agreement(
    cs_tags: list[list[str | None]],
) -> tuple[str, float]:
    """Return the plurality consensus and its minimum per-position support."""
    cs_consensus: list[str] = []
    position_agreements: list[float] = []
    for position_tags in zip(*cs_tags, strict=False):
        # Remove the None that is compensating for the insufficient lead length.
        covered_tags = [tag for tag in position_tags if tag]
        # A gap between non-overlapping reads has no consensus information.
        if not covered_tags:
            continue

        # Get the most common cs tag(s)
        most_common_tags = Counter(covered_tags).most_common()
        most_common_count = most_common_tags[0][1]
        position_agreements.append(most_common_count / len(covered_tags))

        # If there's a unique most common tag, return it
        most_common_tag, _ = most_common_tags[0]
        if (
            len(most_common_tags) == 1
            or most_common_tags[0][1] != most_common_tags[1][1]
        ):
            cs_consensus.append(most_common_tag)
            continue
        # If the most common tag is not unique (multimodal), return the first *mutated* mode
        tied_modes = [
            tag for tag, count in most_common_tags if count == most_common_count
        ]
        selected_tag = next(
            (tag for tag in tied_modes if _is_mutation_tag(tag)), tied_modes[0]
        )
        cs_consensus.append(selected_tag)

    agreement = min(position_agreements, default=1.0)
    return _format_consensus(cs_consensus), agreement


def get_consensus(cs_tags: list[list[str | None]]) -> str:
    cs_consensus, _ = _get_consensus_and_agreement(cs_tags)
    return cs_consensus


def _validate_min_agreement(min_agreement: Real) -> float:
    if isinstance(min_agreement, bool) or not isinstance(min_agreement, Real):
        raise TypeError("min_agreement must be a real number")

    agreement = float(min_agreement)
    if not math.isfinite(agreement) or not 0 <= agreement <= 1:
        raise ValueError("min_agreement must be a finite number between 0 and 1")
    return agreement


def _reference_length(cs_operations: list[str]) -> int:
    reference_length = 0
    for operation in cs_operations:
        if operation.startswith(("=", "-")):
            reference_length += len(operation) - 1
        elif operation.startswith("*"):
            reference_length += 1
        elif operation.startswith("~"):
            intron_length = re.search(r"[0-9]+", operation)
            if intron_length is not None:
                reference_length += int(intron_length.group())
    return reference_length


def _query_sequence_in_interval(
    cs_operations: list[str],
    position: int,
    interval_start: int,
    interval_end: int,
) -> str:
    """Reconstruct query bases emitted within an inclusive reference interval."""
    reference_position = position
    query_sequence = []

    for operation in cs_operations:
        if operation.startswith("="):
            matches = operation[1:]
            operation_end = reference_position + len(matches) - 1
            overlap_start = max(reference_position, interval_start)
            overlap_end = min(operation_end, interval_end)
            if overlap_start <= overlap_end:
                slice_start = overlap_start - reference_position
                slice_end = overlap_end - reference_position + 1
                query_sequence.append(matches[slice_start:slice_end])
            reference_position = operation_end + 1
        elif operation.startswith("*"):
            if interval_start <= reference_position <= interval_end:
                query_sequence.append(operation[-1].upper())
            reference_position += 1
        elif operation.startswith("+"):
            insertion_anchor = reference_position - 1
            if interval_start <= insertion_anchor <= interval_end:
                query_sequence.append(operation[1:].upper())
            elif reference_position == position == interval_start:
                # Preserve a leading insertion when both reads start at this interval.
                query_sequence.append(operation[1:].upper())
        elif operation.startswith("-"):
            reference_position += len(operation) - 1
        elif operation.startswith("~"):
            intron_length = re.search(r"[0-9]+", operation)
            if intron_length is not None:
                reference_position += int(intron_length.group())

    return "".join(query_sequence)


def _levenshtein_distance(sequence_1: str, sequence_2: str) -> int:
    """Calculate unit-cost Levenshtein distance with linear memory."""
    if sequence_1 == sequence_2:
        return 0
    if len(sequence_1) < len(sequence_2):
        sequence_1, sequence_2 = sequence_2, sequence_1
    if not sequence_2:
        return len(sequence_1)

    previous_row = list(range(len(sequence_2) + 1))
    for row_index, base_1 in enumerate(sequence_1, start=1):
        current_row = [row_index]
        for column_index, base_2 in enumerate(sequence_2, start=1):
            insertion = current_row[column_index - 1] + 1
            deletion = previous_row[column_index] + 1
            substitution = previous_row[column_index - 1] + (base_1 != base_2)
            current_row.append(min(insertion, deletion, substitution))
        previous_row = current_row
    return previous_row[-1]


def _max_nearest_edit_distance(cs_tags: list[str], positions: list[int]) -> int | None:
    """Return the largest nearest-neighbor distance among overlapping reads."""
    if len(cs_tags) == 1:
        return 0

    operations_by_read = [split(cs_tag) for cs_tag in cs_tags]
    reference_ends = [
        position + _reference_length(operations) - 1
        for operations, position in zip(operations_by_read, positions, strict=True)
    ]
    nearest_distances: list[int | None] = [None] * len(cs_tags)

    for read_1 in range(len(cs_tags) - 1):
        for read_2 in range(read_1 + 1, len(cs_tags)):
            overlap_start = max(positions[read_1], positions[read_2])
            overlap_end = min(reference_ends[read_1], reference_ends[read_2])
            if overlap_start > overlap_end:
                continue

            sequence_1 = _query_sequence_in_interval(
                operations_by_read[read_1],
                positions[read_1],
                overlap_start,
                overlap_end,
            )
            sequence_2 = _query_sequence_in_interval(
                operations_by_read[read_2],
                positions[read_2],
                overlap_start,
                overlap_end,
            )
            distance = _levenshtein_distance(sequence_1, sequence_2)

            for read in (read_1, read_2):
                nearest_distance = nearest_distances[read]
                if nearest_distance is None or distance < nearest_distance:
                    nearest_distances[read] = distance

    if any(distance is None for distance in nearest_distances):
        return None
    return max(distance for distance in nearest_distances if distance is not None)


###########################################################
# main
###########################################################


def consensus(
    cs_tags: list[str],
    positions: list[int],
    prefix: bool = False,
    *,
    min_agreement: Real | None = None,
    return_result: bool = False,
) -> str | dict[str, str | bool | float | int | None]:
    """Generate a consensus of cs tags and optionally report its quality.

    Args:
        cs_tags (list): cs tags in the **long** format
        positions (list): 1-based leftmost mapping position (4th column in SAM file)
        prefix (bool, optional): Whether to add the prefix 'cs:Z:' to the cs tag. Defaults to False
        min_agreement (float, optional): Minimum required per-position agreement,
            between 0 and 1. Specifying this returns a quality-result dictionary.
        return_result (bool, optional): Return a quality-result dictionary even
            when ``min_agreement`` is not specified. Defaults to False.

    Return:
        str | dict: A long-format consensus string by default. Quality requests
        return a dictionary containing ``consensus``, ``passed``, ``agreement``,
        and ``max_edit_distance``.

    Example:
        >>> import cstag
        >>> cs_tags = ["=ACGT", "=AC*gt=T", "=C*gt=T", "=C*gt=T", "=ACT+ccc=T"]
        >>> positions = [1,1,1,2,1]
        >>> cstag.consensus(cs_tags, positions)
        '=AC*gt=T'
        >>> cstag.consensus(["=ACGT", "=ACGT", "=ACGT", "=AC*gt=T"], [1, 1, 1, 1], min_agreement=0.75)
        {'consensus': '=ACGT', 'passed': True, 'agreement': 0.75, 'max_edit_distance': 1}
    """
    if not (len(cs_tags) == len(positions) > 0):
        raise ValueError("Element numbers of each argument must be the same")

    for cs_tag in cs_tags:
        validate_cs_tag(cs_tag)
        validate_long_format(cs_tag)

    validated_min_agreement = (
        None if min_agreement is None else _validate_min_agreement(min_agreement)
    )

    cs_tags_normalized_length = normalize_read_lengths(cs_tags, positions)
    cs_consensus, agreement = _get_consensus_and_agreement(cs_tags_normalized_length)
    cs_consensus = f"cs:Z:{cs_consensus}" if prefix else cs_consensus

    if validated_min_agreement is None and not return_result:
        return cs_consensus

    return {
        "consensus": cs_consensus,
        "passed": validated_min_agreement is None
        or agreement >= validated_min_agreement,
        "agreement": agreement,
        "max_edit_distance": _max_nearest_edit_distance(cs_tags, positions),
    }
